require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 30

Rspec/MultipleExpectations:
  Enabled: false

Rspec/ExampleLength:
  Enabled: false

