name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '40 8 * * MON'
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      max-parallel: 6
      matrix:
        set:
          - ruby-version: '4.0'
            redis-version: '8.2'
          - ruby-version: '4.0'
            redis-version: '8.0'
          - ruby-version: '4.0'
            redis-version: '7.4'
          - ruby-version: '3.4'
            redis-version: '8.2'
          - ruby-version: '3.3'
            redis-version: '8.2'

    services:
      redis:
        image: redis:${{ matrix.set.redis-version }}
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.set.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.set.ruby-version }}
          bundler-cache: true

      - name: Rackup test web server
        run: bundle exec rake throttle_server:start_daemon

      - name: Run tests
        run: bundle exec rspec -fd
