name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '40 8 * * MON'
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      max-parallel: 6
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', ruby-head]
        redis-version: ['5.0', '6.0', '6.2', '7.0', '7.2', latest]

    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Rackup test web server
        run: bundle exec rake throttle_server:start_daemon

      - name: Run tests
        run: bundle exec rspec -fd
